theme: minima

title: Jonathan Lee's GitHub Blog
author: Joanthan Lee
email: jonodjlee.github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A small blog about my GitHub work.

# social links
twitter_username: jonodjlee # DO NOT include the @ character, or else the build will fail!
github_username:  jonodjlee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
